### ISSUE TITLE
[bug] 页面打开是空白

### ISSUE THREAD

**Issue by Mcayear** [carolcoral/plugin-afdian#7]
## 演示
https://blog.9991565.xyz/afdian

## 插件基本信息
![Screenshot_20241022_163852_com_microsoft_emmx_ChromeTabbedActivity](https://github.com/user-attachments/assets/9fb9c459-bc98-4ba6-89a4-e1cb2b26eec8)

## 环境信息
版本 [2.20.5](https://www.lxware.cn/docs/helpcenter/halo-pro/changlog)

构建时间 2024-10-18 21:41
Git Commit
0e2ad5e
Java
IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
数据库 PostgreSQL / 17.0
操作系统 Linux 5.15.0-124-generic / amd64
系统时区 Asia/Shanghai
系统语言 en_US

**Comment by carolcoral** [comment]
没有人给你赞助，那获取到的内容肯定是空白的啊，你可以对比下接口获取结果，下面是我的返回数据：

<img width="905" alt="image" src="https://github.com/user-attachments/assets/e518cb50-c7eb-46fe-af13-ca162b1a0c01">

下面这个是你的返回数据：
```json
{
  "ec": 200,
  "em": "sponsor",
  "data": {
    "total_count": 0,
    "total_page": 0,
    "list": [],
    "request": {
      "user_id": "ac938690d99511ecb28852540025c377",
      "params": "{\"page\":1}",
      "ts": 1729651058,
      "sign": "87ed28533f86767fd26d0004141382c5"
    }
  }
}
```

插件提供了返回接口API的，你可以自行测试：
* 文档地址：https://blog.xindu.site/docs/plugin-afdian/interface
* 获取赞赏用户列表：https://blog.9991565.xyz/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-afdian/afdian/getSponsorList
