### ISSUE TITLE
侧边栏“爱发电”无法正确跳转页面

### ISSUE THREAD

**Issue by chengzequn** [carolcoral/plugin-afdian#8]
右侧栏的“爱发电”点击之后无法正确跳转到爱发电主页

**Comment by carolcoral** [comment]
有没有站点让我测试下，我看看是哪个地方问题

**Comment by carolcoral** [comment]
你可能说的是侧边栏的赞助用户无法正常访问哇，那个在hao主题里面修复，我已经去修复了，等版本更新吧
https://github.com/chengzhongxue/halo-theme-hao/releases/tag/v1.6.1

**Comment by chengzequn** [comment]
![image](https://github.com/user-attachments/assets/2f8ceb51-b8f9-4ceb-94d3-938758e28752)
就是点击这个黄色区域，没有跳转到到正确的地址。https://threeant.cn
好的，谢谢你。那我先把issue关闭了。

**Comment by carolcoral** [comment]
> ![image](https://private-user-images.githubusercontent.com/13833722/385272070-2f8ceb51-b8f9-4ceb-94d3-938758e28752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTg1MDMsIm5iZiI6MTczMTQ1ODIwMywicGF0aCI6Ii8xMzgzMzcyMi8zODUyNzIwNzAtMmY4Y2ViNTEtYjhmOS00Y2ViLTk0ZDMtOTM4NzU4ZTI4NzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDJhNzFlZDNhNTJhODM1ODE4NWI2MzdlM2ExY2Y3Njg5MTU1NmU5OWI2YTQ0N2RiMTI2ZTMxNGU4ZWE1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PjKBvCRgv_zBkqRrcwB_91vCFNiUjr9E9YBl5xSwbVI) 就是点击这个黄色区域，没有跳转到到正确的地址。https://threeant.cn 好的，谢谢你。那我先把issue关闭了。

明白，那就是这个问题，我已经在hao主题处理了
